// Fallback data when Firestore is unavailable or empty

export interface Coach {
  id: string;
  name: string;
  roleTitle: string;
  photo?: string;
  education: string[];
  experiences: string[];
  certifications: string[];
  specialties: string[];
}

export interface Store {
  id: string;
  slug: string;
  name: string;
  city: string;
  district: string;
  address: string;
  phone: string;
}

export const fallbackStores: Store[] = [
  {
    id: 'xindian',
    slug: 'xindian',
    name: '七張店',
    city: '新北市',
    district: '新店區',
    address: '北新路二段 252 號 B1-2',
    phone: '(02) 8914-6428',
  },
  {
    id: 'nanjing',
    slug: 'nanjing',
    name: '南京店',
    city: '台北市',
    district: '中山區',
    address: '南京東路三段 29 號 B1',
    phone: '(02) 2507-4196',
  },
  {
    id: 'songjiang',
    slug: 'songjiang',
    name: '松江店',
    city: '台北市',
    district: '中山區',
    address: '松江路 122 號 B1',
    phone: '(02) 2537-1055',
  },
  {
    id: 'ximending',
    slug: 'ximending',
    name: '西門店',
    city: '台北市',
    district: '中正區',
    address: '寶慶路 39 號',
    phone: '(02) 2370-3245',
  },
];

export const fallbackCoaches: Record<string, Coach[]> = {
  xindian: [
    {
      id: 'xd-1',
      name: '李哲宇',
      roleTitle: '店主管・物理治療師・教練',
      photo: '/images/coaches/xindian/li-zheyu.webp',
      education: ['國立陽明交通大學物理治療暨輔助科技學系'],
      experiences: ['七張店 店主管', '練健康教練培訓講師', '羅東博愛醫院 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'SFMA 動作篩檢認證', 'FMS 功能性動作篩檢認證', 'DNS A Course', 'RPR Level 1'],
      specialties: ['動作優化訓練', '骨骼肌肉系統傷害後訓練', '中高齡肌力訓練'],
    },
    {
      id: 'xd-2',
      name: '劉軒豪',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/xindian/liu-xuanhao.webp',
      education: ['國立台灣大學物理治療學系'],
      experiences: ['新北市私立慈濟護理之家 物理治療師', '振興醫院 物理治療師'],
      certifications: ['物理治療師證照', 'Redcord Neurac 1 紅繩懸吊訓練認證', 'Redcord Neurac 2 紅繩懸吊訓練認證', 'NASM-CES 矯正性運動訓練專家認證'],
      specialties: ['中高齡族群肌力訓練', '骨骼肌肉系統傷害後訓練', '退化性關節炎訓練', '懸吊系統訓練'],
    },
    {
      id: 'xd-3',
      name: '柯雲翔',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/xindian/ke-yunxiang.webp',
      education: ['輔仁大學物理治療學系'],
      experiences: ['骨科診所 物理治療師', '健身工廠 私人教練'],
      certifications: ['物理治療師證照', 'ACE-CPT 私人教練認證', 'SFMA 動作評估系統認證', 'FMS 功能性動作篩檢認證'],
      specialties: ['中高齡族群肌力訓練', '慢性疼痛族群肌力訓練', '動作控制優化訓練'],
    },
    {
      id: 'xd-4',
      name: '林學禮',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/xindian/lin-xueli.webp',
      education: ['國立陽明交通大學物理治療暨輔助科技學系'],
      experiences: ['恆新復健科診所 物理治療師', '桃園長庚醫院 物理治療師'],
      certifications: ['物理治療師證照', 'GYROKINESIS® Level 1', 'NASM-CES', 'Redcord Neurac 1', 'DNS A Course'],
      specialties: ['姿勢控制與骨盆穩定', '呼吸訓練', '術後族群肌力訓練', '脊椎與核心控制訓練'],
    },
    {
      id: 'xd-5',
      name: '楊百恩',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/xindian/yang-baien.webp',
      education: ['國立台灣大學物理治療學系'],
      experiences: ['衛生福利部雙和醫院 物理治療師'],
      certifications: ['物理治療師證照', 'Polestar Pilates Mat', 'ACE-CPT 美國運動協會私人教練'],
      specialties: ['動作控制訓練', '骨骼肌肉系統傷害後訓練', '中高齡肌力訓練'],
    },
    {
      id: 'xd-6',
      name: '陳宣戎',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/xindian/chen-xuanrong.webp',
      education: ['義守大學物理治療學系'],
      experiences: ['安德復復健專科診所 物理治療師', '長安醫院復健科 物理治療師'],
      certifications: ['物理治療師證照', 'Stott Pilates Mat 墊上皮拉提斯認證', 'DNS Exercise Course Part 1 認證', 'ACE-CPT 美國運動協會私人教練證照'],
      specialties: ['中高齡肌力訓練', '懸吊系統訓練', '皮拉提斯訓練', '腰椎骨盆穩定訓練'],
    },
    {
      id: 'xd-7',
      name: '陳冠翰',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/xindian/chen-guanhan.webp',
      education: ['國立台灣大學物理治療學系'],
      experiences: ['振興醫院 物理治療師', '仁康醫院 物理治療師'],
      certifications: ['物理治療師證照', 'Redcord Neurac 1 認證', 'Redcord Neurac 2 認證', 'DNS A/B Course 認證'],
      specialties: ['中高齡肌力訓練', '懸吊系統訓練', '腰椎骨盆穩定訓練'],
    },
    {
      id: 'xd-8',
      name: '姚舜瀚',
      roleTitle: '教練',
      photo: '/images/coaches/xindian/yao-shunhan.webp',
      education: ['國立體育大學競技與教練科學研究所運動教練碩士班', '國立體育大學技擊運動技術學系'],
      experiences: ['三級棒球隊 教練', '國家級武術運動員', '跆拳道道館 館長兼教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'TATHA 台灣肌力及體能訓練協會 Level 1 認證'],
      specialties: ['中高齡肌力訓練', '青少年運動表現訓練', '運動員肌力訓練'],
    },
    {
      id: 'xd-9',
      name: '林芳妤',
      roleTitle: '教練',
      photo: '/images/coaches/xindian/lin-fangyu.webp',
      education: ['國立體育大學休閒產業經營學系'],
      experiences: ['AFAA MAT SCIENCE 墊上核心國際證照講師', '新北市運動中心 專任教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'ViPR 專業教練認證', 'AFAA MAT SCIENCE 墊上核心國際證照'],
      specialties: ['中高齡肌力訓練', '核心穩定訓練', '皮拉提斯課程'],
    },
    {
      id: 'xd-10',
      name: '鄭健寬',
      roleTitle: '教練',
      photo: '/images/coaches/xindian/zheng-jiankuan.webp',
      education: ['國立臺灣師範大學 體育與運動科學系運動科學碩士班', '國立體育大學適應體育學系'],
      experiences: ['World Gym 世界健身俱樂部 自由教練', '身心動作教育學會 身心學 師資培訓'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'SFMA 動作篩檢認證', 'FMS 功能性動作篩檢認證', 'NSCA-CPT 美國國家肌力與體能協會私人教練'],
      specialties: ['身心動作教育', '特殊族群訓練', '中高齡肌力訓練', '功能性動作訓練'],
    },
  ],
  nanjing: [
    {
      id: 'nj-1',
      name: '蕭彥嶸',
      roleTitle: '店主管・物理治療師・教練',
      photo: '/images/coaches/nanjing/xiao-yanrong.webp',
      education: ['中山醫學大學物理治療學系'],
      experiences: ['南京店 店主管', '練健康教練培訓講師', '臺北榮民總醫院 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'NSCA-CPT 美國國家肌力與體能協會私人教練', 'FMS Level 1 功能性動作篩檢'],
      specialties: ['動作優化訓練', '骨骼肌肉系統傷害後訓練', '中高齡肌力訓練'],
    },
    {
      id: 'nj-2',
      name: '鄭宇劭',
      roleTitle: '副店主管・物理治療師・教練',
      photo: '/images/coaches/nanjing/zheng-yushao.webp',
      education: ['輔仁大學物理治療學系'],
      experiences: ['南京店 副店主管', '練健康教練培訓講師', '世大運 場館經理'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'FMS Level 1 功能性動作篩檢', 'Redcord Neurac 1'],
      specialties: ['中高齡肌力訓練', '運動表現提升', '術後復健訓練'],
    },
    {
      id: 'nj-3',
      name: '謝季宏',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/xie-jihong.webp',
      education: ['國立陽明交通大學物理治療暨輔助科技學系'],
      experiences: ['臺北市立聯合醫院 物理治療師', '臺大醫院 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'DNS A/B Course'],
      specialties: ['中高齡肌力訓練', '動作控制訓練', '神經系統疾患訓練'],
    },
    {
      id: 'nj-4',
      name: '林星辰',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/lin-xingchen.webp',
      education: ['國立成功大學物理治療學系'],
      experiences: ['成大醫院 物理治療師', '骨科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'NASM-CES 矯正性運動訓練專家'],
      specialties: ['中高齡肌力訓練', '骨骼肌肉系統傷害後訓練', '姿勢矯正訓練'],
    },
    {
      id: 'nj-5',
      name: '鍾尚哲',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/zhong-shangzhe.webp',
      education: ['國立台灣大學物理治療學系'],
      experiences: ['台大醫院 物理治療師', '復健科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'DNS A Course'],
      specialties: ['中高齡肌力訓練', '神經系統疾患訓練', '平衡訓練'],
    },
    {
      id: 'nj-6',
      name: '許逸陽',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/xu-yiyang.webp',
      education: ['國立陽明交通大學物理治療暨輔助科技學系'],
      experiences: ['醫學中心 物理治療師', '骨科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'Stott Pilates Mat'],
      specialties: ['中高齡肌力訓練', '動作控制訓練', '皮拉提斯訓練'],
    },
    {
      id: 'nj-7',
      name: '李昆穆',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/li-kunmu.webp',
      education: ['輔仁大學物理治療學系'],
      experiences: ['區域醫院 物理治療師', '長照機構 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'FMS Level 1 功能性動作篩檢'],
      specialties: ['中高齡肌力訓練', '長照族群訓練', '平衡與步態訓練'],
    },
    {
      id: 'nj-8',
      name: '楊宛珧',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/yang-wanyao.webp',
      education: ['國立成功大學物理治療學系'],
      experiences: ['醫學中心 物理治療師', '骨科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'Stott Pilates Mat', 'Stott Pilates Reformer'],
      specialties: ['中高齡肌力訓練', '皮拉提斯訓練', '女性健康訓練'],
    },
    {
      id: 'nj-9',
      name: '王韻婷',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/nanjing/wang-yunting.webp',
      education: ['國立台灣大學物理治療學系'],
      experiences: ['台大醫院 物理治療師', '復健科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'GYROKINESIS® Level 1'],
      specialties: ['中高齡肌力訓練', '動作控制訓練', 'GYROKINESIS® 訓練'],
    },
    {
      id: 'nj-10',
      name: '劉心維',
      roleTitle: '教練',
      photo: '/images/coaches/nanjing/liu-xinwei.webp',
      education: ['國立體育大學運動科學研究所'],
      experiences: ['健身中心 私人教練', '企業健康講座 講師'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'AFAA WT 重量訓練指導員', 'TRX STC 懸吊訓練認證'],
      specialties: ['中高齡肌力訓練', '體態雕塑', '功能性訓練'],
    },
    {
      id: 'nj-11',
      name: '王文郁',
      roleTitle: '教練',
      photo: '/images/coaches/nanjing/wang-wenyu.webp',
      education: ['國立台灣師範大學體育學系'],
      experiences: ['健身中心 私人教練', '運動中心 團課教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'AFAA WT 重量訓練指導員', 'AFAA MAT 墊上核心認證'],
      specialties: ['中高齡肌力訓練', '核心訓練', '體態調整'],
    },
    {
      id: 'nj-12',
      name: '李才昇',
      roleTitle: '教練',
      photo: '/images/coaches/nanjing/li-caisheng.webp',
      education: ['國立體育大學競技運動學系'],
      experiences: ['健身中心 私人教練', '運動員體能訓練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'NSCA-CPT 美國國家肌力與體能協會私人教練'],
      specialties: ['中高齡肌力訓練', '運動表現訓練', '爆發力訓練'],
    },
    {
      id: 'nj-13',
      name: '蔡秉杰',
      roleTitle: '教練',
      photo: '/images/coaches/nanjing/cai-bingjie.webp',
      education: ['國立體育大學休閒產業經營學系'],
      experiences: ['健身中心 私人教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'AFAA WT 重量訓練指導員'],
      specialties: ['中高齡肌力訓練', '體態雕塑', '減脂訓練'],
    },
    {
      id: 'nj-14',
      name: '沈思彤',
      roleTitle: '教練',
      photo: '/images/coaches/nanjing/shen-sitong.webp',
      education: ['國立台北教育大學體育學系'],
      experiences: ['健身中心 私人教練', '瑜珈工作室 瑜珈老師'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'RYT-200 瑜珈師資認證', 'AFAA MAT 墊上核心認證'],
      specialties: ['中高齡肌力訓練', '瑜珈課程', '柔軟度訓練'],
    },
  ],
  songjiang: [
    {
      id: 'sj-1',
      name: '王均祐',
      roleTitle: '練健康店經理',
      photo: '/images/coaches/songjiang/wang-junyou.webp',
      education: ['國立嘉義大學 輔導與諮商學系 學士'],
      experiences: ['練健康西門店教練', '衛生福利部北區老人之家 銀髮族團課老師', '113年諸羅山盃鋼鐵人全國健美錦標賽男子新秀形體', '114年全國水泉菁英盃健力錦標賽', '114年寶礦力路跑21k組', '115年舒跑盃路跑9k組', '115年全國Victory舉重公開賽'],
      certifications: ['ACE-CPT 美國運動協會 - 私人教練證照', '初級救護技術員EMT-1', 'CPR/AED 證照'],
      specialties: ['肌力訓練', '增肌減脂', '中高齡訓練'],
    },
    {
      id: 'sj-2',
      name: '張承玴',
      roleTitle: '練健康教練',
      photo: '/images/coaches/songjiang/zhang-chengxi.webp',
      education: ['世新大學 口語傳播學系 學士'],
      experiences: ['101年國中縣級田徑乙組800公尺、1500公尺 冠軍', '102年國中縣級田徑乙組800公尺、1500公尺 冠軍', '世新大學系際盃排球賽 冠軍'],
      certifications: ['NSCA-CPT 美國國家體能協會-私人教練認證', 'AED-CPR安妮急救教育協會認證'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'sj-3',
      name: '徐睿揚',
      roleTitle: '練健康教練',
      photo: '/images/coaches/songjiang/xu-ruiyang.webp',
      education: ['國立中山大學 機械與機電工程學系 學士'],
      experiences: ['KAT 合作教練'],
      certifications: ['NSCA-CPT 美國國家體能協會-私人教練認證', '紅十字會急救員訓練認證', 'KAT：私人教練培訓、進階阻力、脊柱力學優化、呼吸優化、動作優化', '尋動率：level 1 動作模式整合(MPI)、level 2 動作評估整合(MAI)、運動傷害預防與實作-上肢與下肢、週期性訓練整合', 'NKT Neurokinetic Therapy 神經動能療法Level 1'],
      specialties: ['功能性訓練', '中高齡訓練', '肌力訓練'],
    },
    {
      id: 'sj-4',
      name: '陳重光',
      roleTitle: '練健康教練',
      photo: '/images/coaches/songjiang/chen-zhongguang.webp',
      education: ['銘傳大學 生物科技學系 學士'],
      experiences: ['World Gym 健身教練', '南京中醫藥大學 院際盃籃球賽 冠軍', '105年 桃園市長盃慢速壘球錦標賽 大專組', '106年 全國大專院校生物盃籃球賽'],
      certifications: ['ACE-CPT美國運動委員會-私人教練認證', '體適能C級指導員', '中國醫藥大學CPR+AED認證', '練健康 中高齡訓練研習', '起動教育 全擴張呼吸訓練研習', 'ISCA 國際運動按摩技術員認證', 'WG 肩關節夾擠五十肩矯正應用研習'],
      specialties: ['肌力訓練', '增肌減脂', '功能性訓練'],
    },
    {
      id: 'sj-5',
      name: '楊君澤',
      roleTitle: '練健康教練',
      photo: '',
      education: ['東海大學 會計系 學士'],
      experiences: ['安永聯合會計師事務所 審計部組長', '資誠聯合會計師事務所 審計部外商組副理', '介大會計師事務所 審計部經理', '109年台北渣打馬拉松 21K組', '115年富士山虛擬馬拉松 42K組'],
      certifications: ['ACE-CPT美國運動委員會-私人教練認證', '練健康 中高齡訓練研習', '台灣AED推廣教育協會CPR+AED認證'],
      specialties: ['肌力訓練', '中高齡訓練', '增肌減脂'],
    },
    {
      id: 'sj-6',
      name: '蔡侑儒',
      roleTitle: '練健康教練',
      photo: '',
      education: ['輔仁大學資訊管理學系 學士', '外貿協會國際貿易課程 結業'],
      experiences: ['2016 台北渣打馬拉松 21K組', '2016 台北富邦馬拉松 42K組', '2017 Challenge Taiwan 國際鐵人賽 51.5組', '2018 tSt 鐵人三項聯賽暨鐵人兩項 51.5組', '2018 台北渣打馬拉松 21K組', '2019 日月潭國際萬人泳渡活動', '2023 TBA中華民國自行車協會 360KM 一日北高', '2023 LAVA TRI 玩賽樂園鐵人三項 51.5組', '2023 玉山單攻國際挑戰賽', '2026 斯巴達越野賽 21K組'],
      certifications: ['NASM-CPT 美國國家運動醫學學院 私人教練', '中華民國衝浪協會初級教練證', '中華民國水上救生協會救生員', '匹克球丙級運動裁判證'],
      specialties: ['肌力訓練', '中高齡訓練', '增肌減脂'],
    },
    {
      id: 'sj-7',
      name: '張子誼',
      roleTitle: '練健康教練',
      photo: '',
      education: ['大葉大學工業關係學系 學士'],
      experiences: ['2020年優漾盃國際健力單項硬舉公開賽-長青組亞軍', '2025年開蘭盃九九力士交流賽-六角槓硬舉'],
      certifications: ['ACE-CPT美國運動委員會 私人教練證照'],
      specialties: ['肌力訓練', '中高齡訓練'],
    },
  ],
  ximending: [
    {
      id: 'xm-1',
      name: '陳亮宇',
      roleTitle: '店主管・物理治療師・教練',
      photo: '/images/coaches/ximending/chen-liangyu.webp',
      education: ['國立陽明交通大學物理治療暨輔助科技學系'],
      experiences: ['西門店 店主管', '練健康教練培訓講師', '台北市立聯合醫院 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'NSCA-CPT 美國國家肌力與體能協會私人教練', 'FMS Level 1 功能性動作篩檢'],
      specialties: ['動作優化訓練', '骨骼肌肉系統傷害後訓練', '中高齡肌力訓練'],
    },
    {
      id: 'xm-2',
      name: '林亞儒',
      roleTitle: '副店主管・物理治療師・教練',
      photo: '/images/coaches/ximending/lin-yaru.webp',
      education: ['長庚大學物理治療學系'],
      experiences: ['西門店 副店主管', '練健康教練培訓講師', '林口長庚醫院 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'Stott Pilates Mat', 'Stott Pilates Reformer'],
      specialties: ['中高齡肌力訓練', '皮拉提斯訓練', '女性健康訓練'],
    },
    {
      id: 'xm-3',
      name: '趙世剛',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/ximending/zhao-shigang.webp',
      education: ['中山醫學大學物理治療學系'],
      experiences: ['台中榮民總醫院 物理治療師', '骨科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'NASM-CES 矯正性運動訓練專家'],
      specialties: ['中高齡肌力訓練', '骨骼肌肉系統傷害後訓練', '姿勢矯正訓練'],
    },
    {
      id: 'xm-4',
      name: '吳貫宇',
      roleTitle: '呼吸治療師・教練',
      photo: '/images/coaches/ximending/wu-guanyu.webp',
      education: ['長庚大學呼吸治療學系'],
      experiences: ['彰化基督教醫院 呼吸治療師', '胸腔內科診所 呼吸治療師'],
      certifications: ['呼吸治療師證照', 'ACE-CPT 美國運動協會私人教練', 'FMS Level 1 功能性動作篩檢'],
      specialties: ['中高齡肌力訓練', '心肺功能訓練', '術後族群訓練'],
    },
    {
      id: 'xm-5',
      name: '鍾緯沛',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/ximending/zhong-sipei.webp',
      education: ['國立成功大學物理治療學系'],
      experiences: ['成大醫院 物理治療師', '復健科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'Stott Pilates Mat'],
      specialties: ['中高齡肌力訓練', '皮拉提斯訓練', '動作控制訓練'],
    },
    {
      id: 'xm-6',
      name: '范瑞瑜',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/ximending/fan-ruiyu.webp',
      education: ['高雄醫學大學物理治療學系'],
      experiences: ['高雄長庚醫院 物理治療師', '骨科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'FMS Level 1 功能性動作篩檢'],
      specialties: ['中高齡肌力訓練', '骨骼肌肉系統傷害後訓練', '平衡訓練'],
    },
    {
      id: 'xm-7',
      name: '陳品瀚',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/ximending/chen-pinhan.webp',
      education: ['輔仁大學物理治療學系'],
      experiences: ['台北馬偕醫院 物理治療師', '復健科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'DNS A Course'],
      specialties: ['中高齡肌力訓練', '動作控制訓練', '核心穩定訓練'],
    },
    {
      id: 'xm-8',
      name: '朱兆煜',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/ximending/zhu-zhaoyu.webp',
      education: ['國立台灣大學物理治療學系'],
      experiences: ['台大醫院 物理治療師', '骨科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'SFMA 動作評估系統'],
      specialties: ['中高齡肌力訓練', '骨骼肌肉系統傷害後訓練', '動作優化訓練'],
    },
    {
      id: 'xm-9',
      name: '陳詠佑',
      roleTitle: '物理治療師・教練',
      photo: '/images/coaches/ximending/chen-yongyou.webp',
      education: ['中山醫學大學物理治療學系'],
      experiences: ['台中榮民總醫院 物理治療師', '復健科診所 物理治療師'],
      certifications: ['物理治療師證照', 'ACE-CPT 美國運動協會私人教練', 'FMS Level 1 功能性動作篩檢'],
      specialties: ['中高齡肌力訓練', '神經系統疾患訓練', '平衡與步態訓練'],
    },
    {
      id: 'xm-10',
      name: '許雅淇',
      roleTitle: '教練',
      photo: '/images/coaches/ximending/xu-yaqi.webp',
      education: ['國立體育大學休閒產業經營學系'],
      experiences: ['健身中心 私人教練', '運動中心 團課教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'AFAA WT 重量訓練指導員', 'AFAA MAT 墊上核心認證'],
      specialties: ['中高齡肌力訓練', '核心訓練', '體態雕塑'],
    },
    {
      id: 'xm-11',
      name: '林哲玄',
      roleTitle: '教練',
      photo: '/images/coaches/ximending/lin-zhexuan.webp',
      education: ['國立台灣師範大學體育學系'],
      experiences: ['健身中心 私人教練', '運動表現訓練中心 教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'NSCA-CPT 美國國家肌力與體能協會私人教練', 'TRX STC 懸吊訓練認證'],
      specialties: ['中高齡肌力訓練', '功能性訓練', '運動表現訓練'],
    },
    {
      id: 'xm-12',
      name: '邱子豪',
      roleTitle: '教練',
      photo: '/images/coaches/ximending/qiu-zihao.webp',
      education: ['國立體育大學競技運動學系'],
      experiences: ['健身中心 私人教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'AFAA WT 重量訓練指導員', 'KBC 壺鈴教練認證'],
      specialties: ['中高齡肌力訓練', '壺鈴訓練', '體態雕塑'],
    },
    {
      id: 'xm-13',
      name: '陳泊維',
      roleTitle: '教練',
      photo: '/images/coaches/ximending/chen-bowei.webp',
      education: ['國立台北教育大學體育學系'],
      experiences: ['健身中心 私人教練', '運動中心 體適能教練'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'AFAA WT 重量訓練指導員'],
      specialties: ['中高齡肌力訓練', '功能性訓練', '減脂訓練'],
    },
    {
      id: 'xm-14',
      name: '林誌楷',
      roleTitle: '教練',
      photo: '/images/coaches/ximending/lin-zhikai.webp',
      education: ['國立體育大學運動科學研究所'],
      experiences: ['健身中心 私人教練', '企業健康講座 講師'],
      certifications: ['ACE-CPT 美國運動協會私人教練', 'NSCA-CPT 美國國家肌力與體能協會私人教練', 'TRX STC 懸吊訓練認證'],
      specialties: ['中高齡肌力訓練', '運動表現訓練', '懸吊訓練'],
    },
  ],
};
