// Fallback data when Firestore is unavailable or empty

export interface Coach {
  id: string;
  name: string;
  roleTitle: string;
  photo?: string;
  education: string[];
  experiences: string[];
  certifications: string[];
  specialties: string[];
}

export interface Store {
  id: string;
  slug: string;
  name: string;
  city: string;
  district: string;
  address: string;
  phone: string;
}

export const fallbackStores: Store[] = [
  {
    id: 'xindian',
    slug: 'xindian',
    name: '七張店',
    city: '新北市',
    district: '新店區',
    address: '北新路二段 252 號 B1-2',
    phone: '(02) 8914-6428',
  },
  {
    id: 'nanjing',
    slug: 'nanjing',
    name: '南京店',
    city: '台北市',
    district: '中山區',
    address: '南京東路三段 29 號 B1',
    phone: '(02) 2507-4196',
  },
  {
    id: 'songjiang',
    slug: 'songjiang',
    name: '松江店',
    city: '台北市',
    district: '中山區',
    address: '松江路 122 號 B1',
    phone: '(02) 2537-1055',
  },
  {
    id: 'ximending',
    slug: 'ximending',
    name: '西門店',
    city: '台北市',
    district: '中正區',
    address: '寶慶路 39 號',
    phone: '(02) 2370-3245',
  },
];

export const fallbackCoaches: Record<string, Coach[]> = {
  xindian: [
    {
      id: 'xd-1',
      name: '李哲宇',
      roleTitle: '練健康店經理',
      photo: '/images/coaches/xindian/li-zheyu.webp',
      education: ['國立高雄科技大學 土木工程系 學士'],
      experiences: ['WorldGym世界健身 儲備主任'],
      certifications: ['ACE-CPT 美國運動協會-私人教練證照', 'TRX-STC 懸吊訓練師', 'ISCA 國際C級壺鈴教練證', 'ISCA 國際B級壺鈴研習證', '中華民國健身運動協會-體適能健身C級指導員認證', 'CPR/AED 證照'],
      specialties: ['功能性訓練', '中高齡訓練', '肌力訓練'],
    },
    {
      id: 'xd-2',
      name: '劉軒豪',
      roleTitle: '練健康教練',
      photo: '/images/coaches/xindian/liu-xuanhao.webp',
      education: ['天主教輔仁大學 社會學系 學士'],
      experiences: ['天主教輔仁大學 乙組排球隊 104級 隊長', '102學年度 一般組大專排球聯賽 亞軍', '103學年度 一般組大專排球聯賽 季軍'],
      certifications: ['NSCA - CPT美國肌力與體能協會-私人教練證照', 'CMAS 一星潛水員/OPEN WATER SCUBA DIVER', '紅十字會救生員急救證', 'CPR/AED證', 'PADI Advanced Open Water Diver進階開放水域潛水員'],
      specialties: ['功能性訓練', '肌力訓練', '中高齡訓練'],
    },
    {
      id: 'xd-3',
      name: '柯雲翔',
      roleTitle: '練健康教練',
      photo: '/images/coaches/xindian/ke-yunxiang.webp',
      education: ['輔仁大學 運動休閒管理學系 學士'],
      experiences: ['永平國小 跆拳道社團老師', '公館運動中心 巡場教練', '健身工廠 私人教練'],
      certifications: ['ACE-CPT 美國運動委員會-私人教練證', '台灣體適能運動發展協會-銀髮族性體適能教練證', '醫適能-疼痛科學及下背痛訓練專家', 'G動學-上肢整合訓練', 'CPR/AED證', '國際跆拳道黑帶三段證書'],
      specialties: ['肌力訓練', '中高齡訓練', '體態雕塑'],
    },
    {
      id: 'xd-4',
      name: '陳冠翰',
      roleTitle: '練健康教練',
      photo: '/images/coaches/xindian/chen-guanhan.webp',
      education: ['陽明大學 生命科學系暨基因體研究所 碩士', '東海大學 生命科學系生物醫學組 學士'],
      experiences: ['成吉思汗健身俱樂部 私人教練', '長庚大學 生物醫學系 研究助理'],
      certifications: ['怪獸訓練-肌力與體能教練C級', 'CPR/AED', '夢想運動x爆發力工作室聯名舉重研習'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'xd-5',
      name: '鄭健寬',
      roleTitle: '練健康教練/職能治療師',
      photo: '/images/coaches/xindian/zheng-jiankuan.webp',
      education: ['輔仁大學 職能治療學系'],
      experiences: ['財團法人台灣省私立高雄仁愛之家附設慈惠醫院-精神科職能治療師', '愛迪樂居家職能治療所-職能治療師', '預防及延緩失能方案指導員'],
      certifications: ['中華民國職能治療師', '長照Level-3認證', '怪獸訓練-抗老化肌力與體能教練', 'ACSM-CPT 美國運動醫學會證照'],
      specialties: ['中高齡訓練', '特殊族群訓練', '肌力訓練'],
    },
    {
      id: 'xd-6',
      name: '姚舜瀚',
      roleTitle: '練健康教練/運動防護員',
      photo: '/images/coaches/xindian/yao-shunhan.webp',
      education: ['國立體育大學 運動保健學系 碩士', '高雄醫學大學 運動醫學系 學士'],
      experiences: ['國立臺灣師範大學聘任運動防護員', '114學年度UBA臺灣師大隨隊防護員', '115學年度UBA臺灣師大隨隊防護員', '114年全大運臺灣師大田徑隊隨隊防護員', '2023年U-15世界青少棒錦標賽隨隊防護員', '2024年U-15亞洲青少棒錦標賽隨隊防護員'],
      certifications: ['運動部運動防護員', 'NSCA-CSCS 美國肌力體能訓練專家', '緊急救護技術員EMT-1', 'Redcord Active認證', 'Dynamic Tape認證'],
      specialties: ['運動傷害防護', '肌力訓練與動作優化', '中高齡訓練'],
    },
    {
      id: 'xd-7',
      name: '林芳妤',
      roleTitle: '練健康教練/物理治療師',
      photo: '/images/coaches/xindian/lin-fangyu.webp',
      education: ['輔英科技大學 物理治療學系'],
      experiences: ['永和復康醫院 物理治療師', '昌惟骨科診所 物理治療師'],
      certifications: ['高考合格物理治療師', 'NSCA -CPT美國國家體能協會-私人教練認證', 'CPR+AED紅十字會急救證', 'SFMA Level1 精選功能性動作評估', 'DNS Clinical courses(Medical)_ Basic Course  A課程'],
      specialties: ['中高齡訓練', '功能性訓練', '特殊族群訓練'],
    },
    {
      id: 'xd-8',
      name: '楊百恩',
      roleTitle: '練健康教練',
      photo: '/images/coaches/xindian/yang-baien.webp',
      education: ['國立台灣科技大學 醫學工程研究所 碩士', '南台科技大學 電機系生物醫學電子組 學士'],
      experiences: ['2020-2025 智慧型運動紡織品 研究員', '2022-2024 銀髮族居家訓練系統開發', '2024-2025 瑜珈姿勢校正及遠端訓練系統開發'],
      certifications: ['ACE-CPT 美國運動協會 - 私人教練證照', '體適能健身 C 級指導員', '緊急救護技術員EMT-1'],
      specialties: ['肌力訓練', '增肌減脂', '功能性訓練'],
    },
    {
      id: 'xd-9',
      name: '林學禮',
      roleTitle: '練健康教練',
      photo: '/images/coaches/xindian/lin-xueli.webp',
      education: ['美國德州大學達拉斯分校 會計管理學系碩士', '加拿大特倫特大學 經濟學系學士'],
      experiences: ['2014 加拿大溫哥華華人籃球聯賽 複賽晉級', '2007 達拉斯地區性籃球聯賽 複賽晉級', '2004 NBA 3on3 地區預賽出賽', '2004/2005 校內3on3籃球聯賽總召'],
      certifications: ['ACE-CPT 美國運動協會 - 私人教練證照', 'AED-CPR 安妮急救教育協會認證'],
      specialties: ['肌力訓練', '增肌減脂', '中高齡訓練'],
    },
    {
      id: 'xd-10',
      name: '陳宣戎',
      roleTitle: '練健康教練',
      photo: '/images/coaches/xindian/chen-xuanrong.webp',
      education: ['國立臺灣師範大學 公民教育與活動領導學系'],
      experiences: ['南山人壽國道馬拉松-5K接力組', '追火車鐵道馬拉松接力-第二棒15K', '超核心健身中心 駐場教練'],
      certifications: ['體適能健身 C 級指導員', 'NSCA-CSCS 美國肌力體能訓練專家'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'xd-11',
      name: '陳存灝',
      roleTitle: '練健康教練/物理治療師',
      photo: '',
      education: ['國立陽明交通大學物理治療暨輔助科技學系 學士'],
      experiences: ['114年 世壯運籃球 場邊防護員', '練健康西門店 物理治療背景教練', 'Motion Potion 動作處方籤 播客主持人'],
      certifications: ['高考合格物理治療師', 'ACSM-CPT 美國運動醫學會認證健身教練', 'CPR+AED證照'],
      specialties: ['特殊族群訓練', '中高齡訓練', '功能性訓練'],
    },
  ],
  nanjing: [
    {
      id: 'nj-1',
      name: '蕭彥嶸',
      roleTitle: '練健康店經理',
      photo: '/images/coaches/nanjing/xiao-yanrong.webp',
      education: ['高雄醫學大學 運動醫學系 學士'],
      experiences: ['高雄醫學大學 棒球隊', '109年全國菁英盃健力錦標賽', '富邦悍將實習運動防護員'],
      certifications: ['ACSM-EP', '教育部體育署運動防護員', 'EMT-1'],
      specialties: ['健力三項', '運動傷害防護', '肌力訓練'],
    },
    {
      id: 'nj-2',
      name: '鄭宇劭',
      roleTitle: '練健康教練/物理治療師',
      photo: '/images/coaches/nanjing/zheng-yushao.webp',
      education: ['國立體育大學 競技與教練科學研究所 碩士', '中山醫學大學 物理治療系 學士'],
      experiences: ['108至今 滑輪溜冰體能訓練師單項運動協會運動傷害及動作分析講師', '105-108年 朝盈股份有限公司物理治療督導', '106-109年 競速滑冰世界盃隨隊物理治療師', '106年 世大運運動傷害防護組場館經理'],
      certifications: ['中華民國物理治療師', 'NSCA-CSCS 美國肌力體能訓練專家', 'ACE-CPT 美國運動協會-私人教練證照'],
      specialties: ['中高齡訓練', '肌力訓練', '術後訓練'],
    },
    {
      id: 'nj-3',
      name: '沈思彤',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/shen-sitong.webp',
      education: ['世新大學傳播管理學系學士'],
      experiences: ['練健康行政專員', '練健康行銷專員', '練健康行銷實習生', '世新大學傳管系系女排隊長'],
      certifications: ['NSCA-CPT 美國國家體能協會-私人教練認證', 'NHE-KBT 運動醫學功能性壺鈴訓練師', '體適能健身C級指導員', '中華民國紅十字會CPR+AED'],
      specialties: ['中高齡訓練', '肌力訓練', '專項訓練'],
    },
    {
      id: 'nj-4',
      name: '蔡秉杰',
      roleTitle: '練健康教練/物理治療師',
      photo: '/images/coaches/nanjing/cai-bingjie.webp',
      education: ['國立臺灣大學 物理治療學系六年制畢業'],
      experiences: ['109學年度台灣大學籃球隊大專男子組公開二級季軍', '110學年度男子籃球大專盃公開一級出賽', '112仁愛國小籃球隊助理教練', '112年校外體育系4-6年級國小籃球營總教練', '112年彰化縣政府國中國小籃球訓練營教練', '114學年度台灣大學籃球隊大專男子組公開二級殿軍', '台灣大學籃球及柔道隊隨隊防護'],
      certifications: ['高考合格物理治療師', 'NSCA-CSCS 美國肌力體能訓練專家', '中華民國紅十字會CPR+AED'],
      specialties: ['專項訓練', '特殊族群訓練', '功能性訓練'],
    },
    {
      id: 'nj-5',
      name: '許逸陽',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/xu-yiyang.webp',
      education: ['國立體育大學 運動保健學士'],
      experiences: ['國立體育大學 體適能中心 健身教練', '林口國民運動中心 實習教練', '鐵人工廠私人教練'],
      certifications: ['AFAA-WT國際重量訓練指導員證照', 'CPR-AED 證照', '教育部體育署國民體適能指導員', 'NSCA-CPT美國肌力體能協會-私人教練證照', 'StrongFirst Girya L1美國力量學院硬式壺鈴教練'],
      specialties: ['動作控制', '功能性訓練', '中高齡訓練'],
    },
    {
      id: 'nj-6',
      name: '楊宛珧',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/yang-wanyao.webp',
      education: ['國立暨南國際大學外國語文學系'],
      experiences: ['普悠瑪鐵人三項113KM', '崇越武嶺盃女子分組第6名', '怪獸訓練體能教練俱樂部第28期'],
      certifications: ['NSCA-CPT美國肌力體能協會-私人教練證照', 'SDI進階開放水域潛水員'],
      specialties: ['肌力訓練', '特殊族群訓練', '中高齡訓練'],
    },
    {
      id: 'nj-7',
      name: '謝季宏',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/xie-jihong.webp',
      education: ['國立宜蘭大學經濟系學士'],
      experiences: ['111年苗栗縣縣長盃健美錦標賽 公開組', '全真瑜伽 True Yoga 私人教練'],
      certifications: ['ACE-CPT美國運動協會-私人教練認證', 'ACE-50+美國運動協會-銀髮族訓練認證', 'TRX教練認證', 'KBC國際壺鈴證照L1', 'Boxercise L1、L2、L3拳擊認證', 'M.E.T神經系統訓練研習', 'TWI運動傷害防護證照', 'Gray Institute 應用功能性科學國際認證'],
      specialties: ['體態雕塑', '拳擊訓練', '中高齡訓練'],
    },
    {
      id: 'nj-8',
      name: '許之丞',
      roleTitle: '練健康教練/物理治療師',
      photo: '',
      education: ['中山醫學大學 物理治療系 學士'],
      experiences: ['中華田徑潛優培訓隊物理治療師(2021)', '中華男足培訓隊物理治療師(2021)', '台灣企業甲級足球聯賽台灣石虎隊-特約物理治療師(2022-2024)', '安和復健科診所 物理治療組長 (2021-2023)', '練健康 物理治療師/教練（2023至今）'],
      certifications: ['中華民國物理治療師證照', 'NSCA-CSCS'],
      specialties: ['專項訓練', '中高齡訓練', '特殊族群訓練'],
    },
    {
      id: 'nj-9',
      name: '劉心維',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/liu-xinwei.webp',
      education: ['國立臺灣大學財務金融學系 學士'],
      experiences: ['臺大財金系籃 副隊長', 'Oikid 兒童線上美語 行銷儲備幹部'],
      certifications: ['NSCA-CPT 美國肌力體能協會-私人教練證照', '怪獸肌力及體能訓練中心 C 級教練', '中華民國健身運動協會 體適能健身C級指導員', 'CPR+AED 證照'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'nj-10',
      name: '李才昇',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/li-caisheng.webp',
      education: ['淡江大學公共行政學系'],
      experiences: ['台北捷運行車專員'],
      certifications: ['TSCA-SCC中華民國運動教練學會肌力與體能丙級', 'IKT國際壺鈴教練 LV1', 'TRX-STC 懸吊訓練師'],
      specialties: ['肌力訓練', '壺鈴訓練', '中高齡訓練'],
    },
    {
      id: 'nj-11',
      name: '李昆穆',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/li-kunmu.webp',
      education: ['龍華科技大學 化工與材料工程學系 學士'],
      experiences: ['博凱音樂用品股份有限公司專員', '莫札特音樂教室 爵士鼓老師', '海盜沖浪 沖浪助教'],
      certifications: ['NSCA-CPT國際個人健身教練', '紅十字會救生員急救證'],
      specialties: ['肌力訓練', '功能性訓練', '中高齡訓練'],
    },
    {
      id: 'nj-12',
      name: '王韻婷',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/wang-yunting.webp',
      education: ['實踐大學 工業產品設計學系'],
      experiences: ['MEandMine 兒童情緒教育產品-產品設計師', '2025台北壺鈴挺舉公開賽', '體研所-筋骨放鬆徒手保健課程'],
      certifications: ['NASM-CPT 美國國家運動醫學學會私人教練證', '壺鈴運動認證Lv.1', 'CPR+AED證照'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'nj-13',
      name: '鍾尚哲',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/zhong-shangzhe.webp',
      education: ['國立中央大學企業管理學系'],
      experiences: ['弘道老人福利基金會 日照中心志工', '國立中央大學健身社 創社社長', '康健雜誌 行銷實習生'],
      certifications: ['ACE-CPT 美國運動協會 私人教練認證', '癌症希望基金會 癌症訓練教練認證', 'CPR+AED證照'],
      specialties: ['中高齡訓練', '肌力訓練', '體態雕塑'],
    },
    {
      id: 'nj-14',
      name: '王文郁',
      roleTitle: '練健康教練',
      photo: '/images/coaches/nanjing/wang-wenyu.webp',
      education: ['國立台北教育大學語文與創作學系創作組'],
      experiences: ['虎鐵健身 行政小編', '賴翠霜舞創劇場', '2022《百態The Frames》沈浸式舞蹈劇場＆實驗裝置展 實習舞者', '2021台南藝術節《他們的故事》舞者/表演者', '2020 素人雙年演出計畫II《他們的故事》舞者/表演者', '2016 OBS Hip Hop battle Best30', '國北教大熱舞社 教學'],
      certifications: ['ACE-CPT 美國運動協會 私人教練認證', '台灣體適能運動發展協會C級健身指導員', 'CPR+AED'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
  ],
  songjiang: [
    {
      id: 'sj-1',
      name: '王均祐',
      roleTitle: '練健康店經理',
      photo: '/images/coaches/songjiang/wang-junyou.webp',
      education: ['國立嘉義大學 輔導與諮商學系 學士'],
      experiences: ['練健康西門店教練', '衛生福利部北區老人之家 銀髮族團課老師', '113年諸羅山盃鋼鐵人全國健美錦標賽男子新秀形體', '114年全國水泉菁英盃健力錦標賽', '114年寶礦力路跑21k組', '115年舒跑盃路跑9k組', '115年全國Victory舉重公開賽'],
      certifications: ['ACE-CPT 美國運動協會 - 私人教練證照', '初級救護技術員EMT-1', 'CPR/AED 證照'],
      specialties: ['肌力訓練', '增肌減脂', '中高齡訓練'],
    },
    {
      id: 'sj-2',
      name: '張承玴',
      roleTitle: '練健康教練',
      photo: '/images/coaches/songjiang/zhang-chengxi.webp',
      education: ['世新大學 口語傳播學系 學士'],
      experiences: ['101年國中縣級田徑乙組800公尺、1500公尺 冠軍', '102年國中縣級田徑乙組800公尺、1500公尺 冠軍', '世新大學系際盃排球賽 冠軍'],
      certifications: ['NSCA-CPT 美國國家體能協會-私人教練認證', 'AED-CPR安妮急救教育協會認證'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'sj-3',
      name: '徐睿揚',
      roleTitle: '練健康教練',
      photo: '/images/coaches/songjiang/xu-ruiyang.webp',
      education: ['國立中山大學 機械與機電工程學系 學士'],
      experiences: ['KAT 合作教練'],
      certifications: ['NSCA-CPT 美國國家體能協會-私人教練認證', '紅十字會急救員訓練認證', 'KAT：私人教練培訓、進階阻力、脊柱力學優化、呼吸優化、動作優化', '尋動率：level 1 動作模式整合(MPI)、level 2 動作評估整合(MAI)、運動傷害預防與實作-上肢與下肢、週期性訓練整合', 'NKT Neurokinetic Therapy 神經動能療法Level 1'],
      specialties: ['功能性訓練', '中高齡訓練', '肌力訓練'],
    },
    {
      id: 'sj-4',
      name: '陳重光',
      roleTitle: '練健康教練',
      photo: '/images/coaches/songjiang/chen-zhongguang.webp',
      education: ['銘傳大學 生物科技學系 學士'],
      experiences: ['World Gym 健身教練', '南京中醫藥大學 院際盃籃球賽 冠軍', '105年 桃園市長盃慢速壘球錦標賽 大專組', '106年 全國大專院校生物盃籃球賽'],
      certifications: ['ACE-CPT美國運動委員會-私人教練認證', '體適能C級指導員', '中國醫藥大學CPR+AED認證', '練健康 中高齡訓練研習', '起動教育 全擴張呼吸訓練研習', 'ISCA 國際運動按摩技術員認證', 'WG 肩關節夾擠五十肩矯正應用研習'],
      specialties: ['肌力訓練', '增肌減脂', '功能性訓練'],
    },
    {
      id: 'sj-5',
      name: '楊君澤',
      roleTitle: '練健康教練',
      photo: '',
      education: ['東海大學 會計系 學士'],
      experiences: ['安永聯合會計師事務所 審計部組長', '資誠聯合會計師事務所 審計部外商組副理', '介大會計師事務所 審計部經理', '109年台北渣打馬拉松 21K組', '115年富士山虛擬馬拉松 42K組'],
      certifications: ['ACE-CPT美國運動委員會-私人教練認證', '練健康 中高齡訓練研習', '台灣AED推廣教育協會CPR+AED認證'],
      specialties: ['肌力訓練', '中高齡訓練', '增肌減脂'],
    },
    {
      id: 'sj-6',
      name: '蔡侑儒',
      roleTitle: '練健康教練',
      photo: '',
      education: ['輔仁大學資訊管理學系 學士', '外貿協會國際貿易課程 結業'],
      experiences: ['2016 台北渣打馬拉松 21K組', '2016 台北富邦馬拉松 42K組', '2017 Challenge Taiwan 國際鐵人賽 51.5組', '2018 tSt 鐵人三項聯賽暨鐵人兩項 51.5組', '2018 台北渣打馬拉松 21K組', '2019 日月潭國際萬人泳渡活動', '2023 TBA中華民國自行車協會 360KM 一日北高', '2023 LAVA TRI 玩賽樂園鐵人三項 51.5組', '2023 玉山單攻國際挑戰賽', '2026 斯巴達越野賽 21K組'],
      certifications: ['NASM-CPT 美國國家運動醫學學院 私人教練', '中華民國衝浪協會初級教練證', '中華民國水上救生協會救生員', '匹克球丙級運動裁判證'],
      specialties: ['肌力訓練', '中高齡訓練', '增肌減脂'],
    },
    {
      id: 'sj-7',
      name: '張子誼',
      roleTitle: '練健康教練',
      photo: '',
      education: ['大葉大學工業關係學系 學士'],
      experiences: ['2020年優漾盃國際健力單項硬舉公開賽-長青組亞軍', '2025年開蘭盃九九力士交流賽-六角槓硬舉'],
      certifications: ['ACE-CPT美國運動委員會 私人教練證照'],
      specialties: ['肌力訓練', '中高齡訓練'],
    },
  ],
  ximending: [
    {
      id: 'xm-1',
      name: '陳亮宇',
      roleTitle: '練健康店經理',
      photo: '/images/coaches/ximending/chen-liangyu.webp',
      education: ['國立臺灣師範大學 臺灣語文學系'],
      experiences: ['113年 秋健身健力公開賽', '113年 全國水泉菁英盃健力錦標賽', '113年 噪嘎那盃單項硬舉公開賽', '114年 桃園市長盃健力錦標賽', '114年 全國水泉菁英盃健力錦標賽', '114年 噪嘎那盃單項硬舉公開賽 分組第三', '練健康西門店教練'],
      certifications: ['ACE-CPT 私人教練證照', 'ACE 營養專家', '體適能C級', 'CPR/AED 證照'],
      specialties: ['健力三項', '肌力訓練', '中高齡訓練'],
    },
    {
      id: 'xm-2',
      name: '林亞儒',
      roleTitle: '練健康副店經理',
      photo: '/images/coaches/ximending/lin-yaru.webp',
      education: ['中國文化大學 勞工關係學系 學士'],
      experiences: ['PT Yoga & Lai\'s Ex 臨床＆運動系統解剖學研習', 'TRX-STC懸吊訓練課程', '台灣動作專家協會-動作整合＆訓練IMT 上肢＋下肢 課程', 'M.A.S.O. 動作分析協同優化- 肩關節、軀幹(腰胸頸) 課程', 'BPS-S 呼吸體態側彎：臨床實務整合訓練-脊椎側彎與體態歪斜 課程', '練健康西門店教練'],
      certifications: ['ACE-CPT 美國運動協會 - 私人教練證照', 'CPR/AED 證照'],
      specialties: ['中高齡訓練', '肌力訓練', '體態雕塑'],
    },
    {
      id: 'xm-3',
      name: '林稚荃',
      roleTitle: '練健康教練/物理治療師',
      photo: '',
      education: ['國立台灣大學 物理治療學系 六年制畢業'],
      experiences: ['2023亞青/亞青少舉重錦標賽中華隊隨隊物理治療師', '2023亞洲盃短道競速滑冰錦標賽中華隊隨隊物理治療師', '國立台灣大學男子籃球隊隨隊物理治療師'],
      certifications: ['高考合格物理治療師', '中華民國健身運動協會 C級體適能指導員', '動態神經肌肉穩定術 Dynamic Neuromuscular Stabilization A、B認證'],
      specialties: ['術後訓練', '特殊族群訓練', '中高齡訓練'],
    },
    {
      id: 'xm-4',
      name: '范瑞瑜',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/fan-ruiyu.webp',
      education: ['世新大學 傳播管理系 學士'],
      experiences: ['臺北市國民小學教師/課後照顧班老師', '獸醫院助理', '北市特寵人員職能認證寵物保姆', '2014 臺北國際龍舟錦標賽 小型龍舟 公開女子組第五名', '2016 Spartan Race Sprint finisher', '2017高雄國際馬拉松 42.195KM', '2019 礁溪酥湖越野賽 10KM'],
      certifications: ['NASM-CPT 美國國家運動醫學學院 私人教練', '中華民國健身運動協會 體適能健身C級指導員', 'CPR-AED紅十字會急救證', 'PADI AOW Diver 進階開放水域潛水員'],
      specialties: ['增肌減脂', '體態雕塑', '中高齡訓練'],
    },
    {
      id: 'xm-5',
      name: '趙世剛',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/zhao-shigang.webp',
      education: ['中國科技大學 企業管理系'],
      experiences: ['2018 鐵人三項 51.5KM', '2019 初全程馬拉松完賽成績2小時58分', '2021 最佳半程馬拉松完賽成績79分', '2022 最佳全程馬拉松完賽成績2小時48分', '2023 臺北國道馬拉松配速員', '馬拉松個人客製化課表安排'],
      certifications: ['NSCA-CPT 美國國家體能協會私人教練', '中華民國體適能發展協會 C級健身指導員', 'CPR-AED紅十字會急救證'],
      specialties: ['專項訓練', '肌力訓練', '中高齡訓練'],
    },
    {
      id: 'xm-6',
      name: '林誌楷',
      roleTitle: '練健康教練/職能治療師',
      photo: '/images/coaches/ximending/lin-zhikai.webp',
      education: ['國立臺灣大學 職能治療學系'],
      experiences: ['謙信銀髮健身房運動指導員', '躍動空間健身房 配合教練', '台大醫院職能治療', '署立台北醫院生理部門職能治療', '2024 嘉義布袋海風長堤鐵人三項56.5km', '2026 普悠瑪鐵人三項113km'],
      certifications: ['美國運動醫學會認證私人教練 ACSM-CPT', '中華民國職能治療師', '中華民國健身運動協會-樂齡體適能指導員', '中華彼拉提斯暨身心健康協會-RM1彼拉提斯證照', 'CPR-AED紅十字會急救證', '中華民國體育署救生員'],
      specialties: ['特殊族群訓練', '中高齡訓練', '肌力訓練'],
    },
    {
      id: 'xm-7',
      name: '林承緯',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/lin-chengwei.webp',
      education: ['中原大學 生物醫學工程學系 學士'],
      experiences: ['2023-PRC 自由潛水賽事 DNF（動態平潛無蹼）100M', '自由潛水教練'],
      certifications: ['NASM-CPT 美國國家運動醫學學院-私人教練證照', 'ISCA-國際C級健身教練', '練健康 中高齡訓練研習', 'AIDA International Freediving 初階自由潛水員（AIDA2）', 'AIDA International Freediving 進階自由潛水員（AIDA3）', 'AIDA International Freediving 高階自由潛水員（AIDA4）', 'AIDA International Freediving 國際自由潛水教練（Instructor）'],
      specialties: ['肌力訓練', '中高齡訓練', '增肌減脂'],
    },
    {
      id: 'xm-8',
      name: '許雅淇',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/xu-yaqi.webp',
      education: ['長庚大學 醫務管理研究所 碩士'],
      experiences: ['114年 全國水泉菁英盃健力錦標賽', '114年 壺鈴實戰-經典動作教程/壺鈴有氧攻略', '113年 科學與實務-臀肌肌肥大'],
      certifications: ['NASM-CPT 美國國家運動醫學學院 私人教練', 'CPR/AED 證照', 'ELEIKO 舉重認證專家Lv.1'],
      specialties: ['肌力訓練', '壺鈴訓練', '中高齡訓練'],
    },
    {
      id: 'xm-9',
      name: '陳詠侑',
      roleTitle: '練健康教練/儲備幹部',
      photo: '/images/coaches/ximending/chen-yongyou.webp',
      education: ['中國科技大學 土木系 學士'],
      experiences: ['108-111年 World gym私人教練', '111年-113年Surmount運動空間天母私人教練'],
      certifications: ['Ace-Cpt personal Trainer 美國運動委員會', 'Medex特殊族群訓練專家（SPES）', 'ESN運動營養學', 'RAD 自我肌筋膜放鬆', '3D maps動態分析及系統表現', 'THUMP-Boxing 拳擊', 'FTI 功能性訓練-戰繩', 'AASFP功能性壺鈴訓練', 'ELEIKO 舉重認證專家Lv.1'],
      specialties: ['中高齡訓練', '功能性訓練', '肌力訓練'],
    },
    {
      id: 'xm-10',
      name: '吳貫宇',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/wu-guanyu.webp',
      education: ['台北醫學大學 呼吸治療系 學士'],
      experiences: ['110-112 彰化基督教醫院呼吸治療師', '113年 秋健身全國健力公開賽', '113年 全國水泉菁英盃健力錦標賽', '114年全國Victory舉重公開賽'],
      certifications: ['高考合格呼吸治療師', 'NSCA-CSCS 美國國家肌力與體能協會 - 肌力體能訓練專家', 'ACLS高級心臟救命術'],
      specialties: ['中高齡訓練', '肌力訓練', '特殊族群訓練'],
    },
    {
      id: 'xm-11',
      name: '鍾絲沛',
      roleTitle: '練健康教練/儲備幹部',
      photo: '/images/coaches/ximending/zhong-sipei.webp',
      education: ['高雄醫學大學 運動醫學系 學士'],
      experiences: ['練健康西門店｜健身教練', '為好診所 C 級長照站｜體適能指導', '114年 壺鈴實戰－經典動作教程／壺鈴有氧攻略', '114年 WE POWER 團體綜合體能賽', '115年 HYROX Taipei'],
      certifications: ['NSCA-CPT美國國家體能協會-私人教練認證', 'AFAA -WT （AFAA 重量訓練指導員）', '教育部體育署 國民體適能指導員(中級)', 'EMT-1（初級救護技術員）'],
      specialties: ['中高齡訓練', '功能性訓練', '壺鈴訓練'],
    },
    {
      id: 'xm-12',
      name: '陳品瀚',
      roleTitle: '練健康教練/物理治療師',
      photo: '/images/coaches/ximending/chen-pinhan.webp',
      education: ['國立陽明大學物理治療暨輔助科技學系 學士'],
      experiences: ['國家運動訓練中心 物理治療師', '中華民國田徑協會 隨隊物理治療師', '中華民國雪車協會 領隊兼物理治療師', '亮點物理治療所 物理治療師'],
      certifications: ['專技高考物理治療師', 'NSCA-CSCS 美國國家肌力與體能協會 - 肌力體能訓練專家', 'NSCA-CSPS 美國國家肌力與體能協會 - 特殊族群訓練專家'],
      specialties: ['特殊族群訓練', '術後訓練', '中高齡訓練'],
    },
    {
      id: 'xm-13',
      name: '盧立軒',
      roleTitle: '練健康教練',
      photo: '',
      education: ['元智大學 資訊管理學系 學士'],
      experiences: ['練健康西門店 教練', '力格運動健護中心  店長', '栖里健身 健身教練', '聚廠樂活運動俱樂部  店經理', '聚廠樂活運動俱樂部  教練部經理', '幫妳顧小孩健身房  健身教練/團課教練'],
      certifications: ['NASM CPT 美國國家運動醫學學院 私人教練', 'NASM CES 美國國家運動醫學學院 運動矯正專家', 'NSCA CSCS 美國肌力體能訓練專家', '中華民國健美協會 C級教練', 'AFAA WT AFAA 重量訓練指導員', 'FTI Kettlebell level 1第一級壺鈴教練證照', 'FTI Kettlebell level 2第二級壺鈴教練證照', 'FTI Battling 戰繩教練證照', 'TRX STC 懸吊證照', '愛表現團課師資認證'],
      specialties: ['體態雕塑', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'xm-14',
      name: '朱兆煜',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/zhu-zhaoyu.webp',
      education: ['東吳大學國際經營與貿易學系'],
      experiences: ['東吳拳擊社社長', '國貿系系排隊長'],
      certifications: ['NASM-CPT 美國國家運動醫學學院 私人教練', 'ISCA 國際運動教練協會 私人教練', '重整評估 上下肢重整研習', '中華民國健身運動協會 體適能健身C級指導員', 'CPR+AED 證照', 'PADI Enriched Air Diver 高氧潛水員', 'PADI Advanced Open Water Diver 進階開放水域潛水員'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'xm-15',
      name: '林哲玄',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/lin-zhexuan.webp',
      education: ['文化大學心理輔導學系'],
      experiences: ['策展空間專案執行', '諮商室個案管理員'],
      certifications: ['NSCA-CPT 美國肌力體能協會-私人教練證照', '中華民國健身運動協會 體適能健身C級指導員', 'CPR+AED 證照'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'xm-16',
      name: '邱子豪',
      roleTitle: '練健康教練',
      photo: '/images/coaches/ximending/qiu-zihao.webp',
      education: ['銘傳大學醫療資訊與管理學系'],
      experiences: ['資訊軟體工程師', '銘傳大學吉他社社長'],
      certifications: ['ACE-CPT美國運動協會-私人教練認證', 'CPR+AED 證照', '體適能C級指導員'],
      specialties: ['肌力訓練', '中高齡訓練', '功能性訓練'],
    },
    {
      id: 'xm-17',
      name: '陳泊維',
      roleTitle: '練健康教練／醫事放射師',
      photo: '/images/coaches/ximending/chen-bowei.webp',
      education: ['義守大學 醫學影像暨放射科學系 學士'],
      experiences: ['台北馬偕醫院 醫事放射師', '臺大醫院 腫瘤醫學部放射師'],
      certifications: ['中華民國醫事放射師', 'NSCA-CSCS肌力體能專家', 'BLS基本救命術'],
      specialties: ['肌力訓練', '體態雕塑', '中高齡訓練'],
    },
  ],
};
